server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**|/permissions/**|/friends-user/**

        - id: friend-service
          uri: lb://friend-service
          predicates:
            - Path=/friends/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
