server:
  port: 8082

spring:
  application:
    name: friend-service

  datasource:
    url: jdbc:postgresql://localhost:5432/friend-service
    username: postgres
    password: mtuanvu1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: friend-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "com.fai.semfour.userservice.dto, com.fai.semfour.friendservice.dto"
    properties:
      spring.json.trusted.packages: "*"
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.value.default.type: com.fai.semfour.friendservice.dto.FriendEvent

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
