server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: mtuanvu1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true
      highlight_sql: true
      jdbc:
        batch_size: 1

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # Hiển thị giá trị tham số SQL
    org.springframework.boot: ERROR

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signerKey: "5jNfSN9nejl7bpKNcfO2J3PB6QBrtg22FuG8DUiHzUxxRta8azatGtPdP8rWTapJ"
  signerKey-refresh-token: "ieuNUR9VajDE2kFJPPflhMNYgSzhlfpc2hv1UmIv00ZtG5yPc6ohNnv/Vyr+mcPJ"
  access-token-valid-duration: 3600000
  refresh-token-valid-duration: 604800000

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger